name: Continuous Integration
on: [pull_request]

jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make output directory
        run: mkdir outputs
      - name: Zipping the directory
        run: |
          cd outputs
          zip -qq -r code.zip . -i libs
          cd ..
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: outputs
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: libs/
          dest: result.zip

      - name: Install zip
        uses: montudor/action-zip@v0.1.0

      - name: Zip output
        run: zip -qq -r function.zip libs
