# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    name: Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8,3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/set-python@v2
        with: 
          python-version: ${{ matrix.python-version }}      
      
      - uses: actions/checkout@v2

      # Linting and dependencies
      - name: Install dependencies
        run: |
          pip install flake8
          pip install pylint
          flake8 main.py
          pylint main.py


